name: Test Action Release Version

on:
  workflow_dispatch:

jobs:
  test-release-version:
    runs-on: "ubuntu-22.04"
    steps:

      - uses: JohnLBevan/action-terragrunt@v4
        with:
          terragrunt-version: 0.55.0
      - name: Validate
        run: terragrunt --version

      - uses: JohnLBevan/action-terragrunt@v4
        with:
          terragrunt-version: latest
      - name: Validate
        run: terragrunt --version
